import SwiftUI

/// A SwiftUI view that guides the user through importing an `rp_pairing_file.plist`
/// generated by JitterbugPair.
///
/// Features:
/// - Displays current pairing status (paired / not paired).
/// - Presents a `.fileImporter` sheet to select the pairing file from the Files app.
/// - Shows instructions for generating the pairing file on a computer.
/// - Displays the imported file name and last-modified date once available.
struct PairingFileImportView: View {

    /// The pairing file manager that handles persistence, validation, and status publishing.
    @StateObject var pairingFileManager: PairingFileManager = PairingFileManager()

    /// Controls presentation of the file importer sheet (iOS 14+).
    @State private var isImporting: Bool = false

    /// Stores any error message to present to the user.
    @State private var errorMessage: String?
    @State private var showErrorAlert: Bool = false

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 24) {

                    // MARK: - Pairing Status Card
                    statusCard

                    // MARK: - Import Action
                    importButton

                    // MARK: - File Details (if paired)
                    if pairingFileManager.isPaired {
                        fileDetailsCard
                    }

                    // MARK: - Instructions
                    instructionsCard
                }
                .padding()
            }
            .navigationTitle("Pairing File")
        }
        .fileImporter(
            isPresented: $isImporting,
            allowedContentTypes: [.propertyList, .data],
            allowsMultipleSelection: false
        ) { result in
            handleImportResult(result)
        }
        .alert("Import Error", isPresented: $showErrorAlert) {
            Button("OK", role: .cancel) { }
        } message: {
            if let message = errorMessage {
                Text(message)
            }
        }
    }

    // MARK: - Subviews

    /// A prominent card showing whether a valid pairing file is present.
    private var statusCard: some View {
        HStack(spacing: 16) {
            Image(systemName: pairingFileManager.isPaired ? "checkmark.shield.fill" : "exclamationmark.shield.fill")
                .font(.system(size: 32))
                .foregroundColor(pairingFileManager.isPaired ? .green : .orange)

            VStack(alignment: .leading, spacing: 4) {
                Text("Pairing Status")
                    .font(.headline)
                Text(pairingFileManager.isPaired ? "Paired" : "Not Paired")
                    .font(.subheadline)
                    .foregroundColor(.secondary)
            }

            Spacer()
        }
        .padding()
        .background(Color(.secondarySystemBackground))
        .cornerRadius(12)
    }

    /// The primary button that triggers the file importer.
    private var importButton: some View {
        Button {
            isImporting = true
        } label: {
            HStack {
                Image(systemName: "doc.badge.arrow.up")
                Text(pairingFileManager.isPaired ? "Replace Pairing File" : "Import Pairing File")
            }
            .font(.headline)
            .foregroundColor(.white)
            .frame(maxWidth: .infinity)
            .padding()
            .background(Color.accentColor)
            .cornerRadius(12)
        }
    }

    /// Shows metadata about the imported file when one exists.
    private var fileDetailsCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Imported File")
                .font(.headline)

            if let name = pairingFileManager.importedFileName {
                DetailRow(icon: "doc.text", label: "File Name", value: name)
            }

            if let date = pairingFileManager.lastModifiedDate {
                DetailRow(
                    icon: "calendar",
                    label: "Last Modified",
                    value: dateFormatter.string(from: date)
                )
            }

            Button(role: .destructive) {
                pairingFileManager.removePairingFile()
            } label: {
                Label("Remove Pairing File", systemImage: "trash")
            }
            .padding(.top, 4)
        }
        .padding()
        .background(Color(.secondarySystemBackground))
        .cornerRadius(12)
    }

    /// Instructional text explaining how to generate the pairing file.
    private var instructionsCard: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("How to Generate a Pairing File")
                .font(.headline)

            Text("1. On your Mac or PC, install JitterbugPair from the StikJIT or StikDebug project.")
                .font(.subheadline)
                .foregroundColor(.secondary)

            Text("2. Connect your iOS device via USB and run JitterbugPair. It will produce a file named \(Text("rp_pairing_file.plist").fontWeight(.semibold)).")
                .font(.subheadline)
                .foregroundColor(.secondary)

            Text("3. AirDrop or transfer the file to this device, then tap Import Pairing File above.")
                .font(.subheadline)
                .foregroundColor(.secondary)
        }
        .padding()
        .background(Color(.secondarySystemBackground))
        .cornerRadius(12)
    }

    // MARK: - Helpers

    /// Processes the result of the `.fileImporter` sheet.
    private func handleImportResult(_ result: Result<[URL], Error>) {
        switch result {
        case .success(let urls):
            guard let url = urls.first else { return }
            Task {
                do {
                    try await pairingFileManager.importPairingFile(from: url)
                } catch let error as PairingFileError {
                    errorMessage = error.localizedDescription
                    showErrorAlert = true
                } catch {
                    errorMessage = error.localizedDescription
                    showErrorAlert = true
                }
            }
        case .failure(let error):
            errorMessage = error.localizedDescription
            showErrorAlert = true
        }
    }

    /// Shared date formatter for the last-modified timestamp.
    private var dateFormatter: DateFormatter {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter
    }
}

// MARK: - Detail Row Helper

/// A reusable row for displaying a labeled value with an icon.
private struct DetailRow: View {
    let icon: String
    let label: String
    let value: String

    var body: some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .foregroundColor(.accentColor)
                .frame(width: 24, height: 24)

            VStack(alignment: .leading, spacing: 2) {
                Text(label)
                    .font(.caption)
                    .foregroundColor(.secondary)
                Text(value)
                    .font(.body)
            }

            Spacer()
        }
    }
}

// MARK: - Preview

struct PairingFileImportView_Previews: PreviewProvider {
    static var previews: some View {
        PairingFileImportView()
    }
}
