import Foundation
import SwiftUI

/// Errors that can occur during pairing file import or validation.
enum PairingFileError: Error, LocalizedError {
    case fileNotFound
    case copyFailed(underlying: Error)
    case invalidFormat
    case missingRequiredKeys([String])
    case unreadable

    var errorDescription: String? {
        switch self {
        case .fileNotFound:
            return "The selected file could not be found."
        case .copyFailed(let error):
            return "Failed to copy the pairing file: \(error.localizedDescription)"
        case .invalidFormat:
            return "The selected file is not a valid plist or pairing file."
        case .missingRequiredKeys(let keys):
            return "Missing required keys: \(keys.joined(separator: ", "))."
        case .unreadable:
            return "The file could not be read."
        }
    }
}

/// Manages the lifecycle of the `rp_pairing_file.plist` used for RPPairing tunnel authentication.
///
/// Responsibilities:
/// - Observing whether a valid pairing file exists in the app's Documents directory.
/// - Importing a pairing file from an external URL (e.g. Files app, AirDrop, or document picker).
/// - Validating the imported plist for required pairing keys before persisting it.
///
/// The manager is marked `@MainActor` because it exposes `@Published` state to SwiftUI.
@MainActor
final class PairingFileManager: ObservableObject {

    /// Published state reflecting whether a pairing file exists and passed basic validation.
    @Published var isPaired: Bool = false

    /// Published filename of the imported pairing file, for UI display.
    @Published var importedFileName: String?

    /// Published last-modified date of the imported pairing file, for UI display.
    @Published var lastModifiedDate: Date?

    /// The expected filename for the persisted pairing file in the Documents directory.
    private let pairingFileName = "rp_pairing_file.plist"

    /// Keys that a valid RPPairing file should contain.
    /// These correspond to the structure generated by JitterbugPair.
    private let requiredKeys = ["DevicePublicKey", "EscrowBag"]

    // MARK: - Initialization

    init() {
        refreshStatus()
    }

    // MARK: - Public API

    /// Returns `true` if a pairing file exists in the app's Documents directory.
    func hasPairingFile() -> Bool {
        let url = pairingFileURL()
        return FileManager.default.fileExists(atPath: url.path)
    }

    /// Imports a pairing file from an external URL, validates it, and copies it into the
    /// app's Documents directory as `rp_pairing_file.plist`.
    ///
    /// - Parameter sourceURL: The URL of the selected file (typically from a document picker
    ///   or file importer). May be a security-scoped resource.
    /// - Throws: `PairingFileError` if the file cannot be read, validated, or copied.
    func importPairingFile(from sourceURL: URL) async throws {
        let validatedData = try await Task.detached(priority: .userInitiated) { () -> Data in
            guard FileManager.default.fileExists(atPath: sourceURL.path) else {
                throw PairingFileError.fileNotFound
            }
            let access = sourceURL.startAccessingSecurityScopedResource()
            defer {
                if access { sourceURL.stopAccessingSecurityScopedResource() }
            }
            let plistData = try Data(contentsOf: sourceURL)
            try await self.validatePairingFile(data: plistData)
            return plistData
        }.value

        let destinationURL = pairingFileURL()
        if FileManager.default.fileExists(atPath: destinationURL.path) {
            try? FileManager.default.removeItem(at: destinationURL)
        }
        try validatedData.write(to: destinationURL)
        refreshStatus()
    }

    /// Removes the persisted pairing file and resets published state.
    func removePairingFile() {
        let url = pairingFileURL()
        if FileManager.default.fileExists(atPath: url.path) {
            try? FileManager.default.removeItem(at: url)
        }
        refreshStatus()
    }

    // MARK: - Private Helpers

    /// Re-evaluates the pairing file on disk and updates `@Published` properties.
    private func refreshStatus() {
        let url = pairingFileURL()
        let exists = FileManager.default.fileExists(atPath: url.path)
        isPaired = exists

        if exists {
            importedFileName = url.lastPathComponent
            if let attrs = try? FileManager.default.attributesOfItem(atPath: url.path) {
                lastModifiedDate = attrs[.modificationDate] as? Date
            }
        } else {
            importedFileName = nil
            lastModifiedDate = nil
        }
    }

    /// Returns the full file URL for the persisted pairing file in the Documents directory.
    private func pairingFileURL() -> URL {
        guard let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
            fatalError("Documents directory unavailable")
        }
        return docs.appendingPathComponent(pairingFileName)
    }

    /// Validates that the provided data is a valid plist dictionary containing all required keys.
    ///
    /// - Parameter data: Raw file data to validate.
    /// - Throws: `PairingFileError` if the data is not a valid plist or required keys are missing.
    private func validatePairingFile(data: Data) throws {
        guard let plist = try? PropertyListSerialization.propertyList(from: data, format: nil) else {
            throw PairingFileError.invalidFormat
        }

        guard let dictionary = plist as? [String: Any] else {
            throw PairingFileError.invalidFormat
        }

        let missingKeys = requiredKeys.filter { dictionary[$0] == nil }
        guard missingKeys.isEmpty else {
            throw PairingFileError.missingRequiredKeys(missingKeys)
        }
    }
}
